export * from "./shortenPrincipalId";
export * from "./encryption";
export * from "./avatar";
// export * from "./trim";
export * from "./isValidAddress";
export * from "./resolveEmail";
export * from "./getFileName";
export * from "./isPublicKey";
export * from "./share";
export * from "./isActiveRoute";
